package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

// systemSSHConfig is the file ssh reads after the user's own config. -F drops it, so the
// wrapper includes it back.
const systemSSHConfig = "/etc/ssh/ssh_config"

// renderSSHWrapper is the config every daemon ssh invocation is started with.
//
// The order is the whole design. ssh keeps the first value it finds for a setting, so a
// Host block the console wrote comes first and wins over a `Host *` default in the
// user's config, while anything it leaves out (ServerAliveInterval, UseKeychain) still
// comes from there. `Match all` has to come before the user's Include: an Include inside
// a Host block applies only to that block, and here it would apply only to the last
// console-added host. The system config comes last because that is where ssh reads it
// when there is no -F.
//
// Every path is absolute and every comment has its own line: ssh_config has no trailing
// comments, so `Include a # note` would be three globs.
func renderSSHWrapper(cfg *Config) string {
	var b strings.Builder
	b.WriteString("# Generated by portkeeperd at startup. Changes here are overwritten.\n")
	b.WriteString("# Hosts added in the Portkeeper console:\n")
	fmt.Fprintf(&b, "Include %s\n", sshQuote(cfg.HostsFile))
	b.WriteString("Match all\n")
	b.WriteString("# Your own ssh config, read and never written:\n")
	fmt.Fprintf(&b, "Include %s\n", sshQuote(cfg.SSHConfigPath))
	fmt.Fprintf(&b, "Include %s\n", systemSSHConfig)
	return b.String()
}

// writeSSHWrapper writes the wrapper, and makes sure the directory the console's hosts
// and known_hosts live in exists. ssh refuses a config file others can write, so both
// the wrapper and its directory are private.
func writeSSHWrapper(cfg *Config) error {
	if cfg.SSHWrapper == "" {
		return nil
	}
	for _, p := range []string{cfg.SSHWrapper, cfg.HostsFile, cfg.KnownHostsFile} {
		if p == "" {
			continue
		}
		if err := os.MkdirAll(filepath.Dir(p), 0o700); err != nil {
			return err
		}
	}
	return writeFileAtomic(cfg.SSHWrapper, []byte(renderSSHWrapper(cfg)))
}

// writeFileAtomic replaces path in one rename, so ssh never reads a half-written config.
func writeFileAtomic(path string, data []byte) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".*")
	if err != nil {
		return err
	}
	name := tmp.Name()
	defer os.Remove(name) // a no-op once the rename has happened
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(name, path)
}

// sshQuote quotes a value for ssh_config when it holds a space. Values are validated
// before they get here: none may contain a quote, a backslash or a control character,
// so there is nothing inside to escape.
func sshQuote(s string) string {
	if strings.ContainsAny(s, " \t") {
		return `"` + s + `"`
	}
	return s
}

// sshDir is the user's ~/.ssh. Only ever listed, for key file names.
func sshDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".ssh")
}

// listIdentities finds private keys by their public halves: a file with a .pub twin is a
// key. Anything that is only named like one (id_*, without .pub) counts too, since keys
// generated elsewhere do not always travel with their .pub. Returned as ~/.ssh/<name>,
// which is how the dialog shows them and how HostsFile stores them.
func listIdentities(dir string) []string {
	out := []string{}
	if dir == "" {
		return out
	}
	ents, err := os.ReadDir(dir)
	if err != nil {
		return out
	}
	names := map[string]bool{}
	for _, e := range ents {
		names[e.Name()] = true
	}
	for _, e := range ents {
		n := e.Name()
		if !e.Type().IsRegular() || strings.HasSuffix(n, ".pub") || strings.HasPrefix(n, ".") {
			continue
		}
		if names[n+".pub"] || strings.HasPrefix(n, "id_") {
			out = append(out, "~/.ssh/"+n)
		}
	}
	return out
}

// fingerprintFor is ssh-keygen, behind a variable so tests do not need a real key.
var fingerprintFor = func(knownHosts []string, key string) string {
	for _, f := range knownHosts {
		out, err := exec.Command("ssh-keygen", "-F", key, "-f", f, "-l").Output()
		if err != nil {
			continue
		}
		for _, line := range strings.Split(string(out), "\n") {
			for _, tok := range strings.Fields(line) {
				if strings.HasPrefix(tok, "SHA256:") {
					return tok
				}
			}
		}
	}
	return ""
}

// hostFingerprint is the recorded key for a host, as the console shows it after a first
// connection so it can be checked. known_hosts keys a non-default port as [host]:port.
func hostFingerprint(cfg *Config, e hostEntry) string {
	name := e.HostName
	if name == "" {
		name = e.Alias
	}
	if e.Port != 0 && e.Port != 22 {
		name = "[" + name + "]:" + strconv.Itoa(e.Port)
	}
	files := []string{}
	if cfg.KnownHostsFile != "" {
		files = append(files, cfg.KnownHostsFile)
	}
	if d := sshDir(); d != "" {
		files = append(files, filepath.Join(d, "known_hosts"))
	}
	return fingerprintFor(files, name)
}
